name = "sveltehole"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

routes = [
    { pattern = "sveltehole.xiyo.dev", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "sveltehole-db"
database_id = "38d4333f-ab95-4027-bb3f-aca38cf85079"