name = "sveltehole"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-09-23"
compatibility_flags = ["nodejs_compat"]

routes = [
    { pattern = "sveltehole.xiyo.dev", custom_domain = true }
]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"